import {
  isFacebookUrl,
  isInstagramUrl,
  isOkRuUrl,
  isPinterestUrl,
  isRutubeUrl,
  isTikTokUrl,
  isTwitterUrl,
  isVimeoUrl,
  isVkUrl,
  isYoutubeUrl,
} from "@/lib/validations/url";
import { Downloader } from "@/types/nav";

export const downloaders: Downloader[] = [
  {
    name: "YouTube",
    value: "youtube",
    href: "/youtube",
    description: "Download videos from YouTube in HD quality",
    logo: "/images/logos/youtube.svg",
    isComingSoon: false,
    isUrlValid: isYoutubeUrl,
  },
  {
    name: "Facebook",
    value: "facebook",
    href: "/facebook",
    description: "Save videos from Facebook posts and reels",
    logo: "/images/logos/facebook.svg",
    isComingSoon: false,
    isUrlValid: isFacebookUrl,
  },
  {
    name: "Instagram",
    value: "instagram",
    href: "/instagram",
    description: "Download Instagram reels, stories, and posts",
    logo: "/images/logos/instagram.svg",
    isComingSoon: false,
    isUrlValid: isInstagramUrl,
  },
  {
    name: "TikTok",
    value: "tiktok",
    href: "/tiktok",
    description: "Download TikTok videos without watermark",
    logo: "/images/logos/tiktok.svg",
    isComingSoon: false,
    isUrlValid: isTikTokUrl,
  },
  {
    name: "Twitter",
    value: "twitter",
    href: "/twitter",
    description: "Download Twitter videos",
    logo: "/images/logos/x_logo.svg",
    isComingSoon: false,
    isUrlValid: isTwitterUrl,
  },
  {
    name: "Vimeo",
    value: "vimeo",
    href: "/vimeo",
    description: "Download videos from Vimeo in high quality",
    logo: "/images/logos/vimeo.svg",
    isComingSoon: false,
    isUrlValid: isVimeoUrl,
  },
  {
    name: "VK",
    value: "vk",
    href: "/vk",
    description: "Download videos and clips from VK",
    logo: "/images/logos/vk_video.svg",
    isComingSoon: false,
    isUrlValid: isVkUrl,
  },
  {
    name: "Rutube",
    value: "rutube",
    href: "/rutube",
    description: "Download videos from Rutube",
    logo: "/images/logos/rutube.svg",
    isComingSoon: false,
    isUrlValid: isRutubeUrl,
  },
  {
    name: "OK.ru",
    value: "okru",
    href: "/okru",
    description: "Download videos from OK.ru (Odnoklassniki)",
    logo: "/images/logos/OK.svg",
    isComingSoon: false,
    isUrlValid: isOkRuUrl,
  },
  {
    name: "Pinterest",
    value: "pinterest",
    href: "/pinterest",
    description: "Download videos and pins from Pinterest",
    logo: "/images/logos/pinterest.svg",
    isComingSoon: false,
    isUrlValid: isPinterestUrl,
  },
];

